gene_expression: '../../data/datastores/gene_expression_data.json'
gene_expression_gene_name: '../../data/datastores/gene_expression_data_gene_name.json'
methylation: '../../data/datastores/methylation_data.json'
overall_survival: '../../data/datastores/overall_survival_data.json'
cpg950_coding_genes: '../../data/datastores/cpg950_coding_genes_data.json'
cpg950_coding_genes_original: '../../data/datastores/cpg950_coding_genes_original_data.json'
gene_associated_methylation: '../../data/datastores/gene_associated_methylation_data.json'