gene_expression: '../../data/datasets/gene_expression_and_overall_survival_dataset.csv'
methylation: '../../data/datasets/methylation_and_overall_survival_dataset.csv'
gene_expression_and_methylation: '../../data/datasets/gene_expression_and_methylation_and_overall_survival_dataset.csv'
gene_expression_with_associated_methylation: '../../data/datasets/gene_expression_with_associated_methylation_and_overall_survival_dataset.csv'