gene_expression: '../../data/datastores/gene_expression/gene_expression_data.json'
gene_expression_gene_name: '../../data/datastores/gene_expression/gene_expression_data_gene_name.json'
methylation: '../../data/datastores/methylation/methylation_data.json'
gene_associated_methylation: '../../data/datastores/methylation/gene_associated_methylation_data.json'
selected_methylation_islands: '../../data/datastores/methylation/selected_methylation_islands_data.json'
gene_associated_methylation_full: '../../data/datastores/methylation/gene_associated_methylation_data_full.json'
selected_methylation_islands_full: '../../data/datastores/methylation/selected_methylation_islands_data_full.json'
overall_survival: '../../data/datastores/overall_survival/overall_survival_data.json'
cpg950_coding_genes: '../../data/datastores/cpg950_coding_genes/cpg950_coding_genes_data.json'
cpg950_coding_genes_original: '../../data/datastores/cpg950_coding_genes/cpg950_coding_genes_original_data.json'