gene_expression: '../../data/datastores/gene_expression_data.json'
methylation: '../../data/datastores/methylation_data.json'
overall_survival: '../../data/datastores/overall_survival_data.json'
cpg950_coding_genes: '../../data/datastores/cpg950_coding_genes.json'