gene_expression: '../../data/datasets/gene_expression_datasets.json'
methylation: '../../data/datasets/methylation_datasets.json'
overall_survival: '../../data/datasets/overall_survival_datasets.json'