gene_expression: 'C:/Users/lucai/Desktop/Magistrale/Tirocinio/Dati/2 - Gene Expression'
methylation: 'C:/Users/lucai/Desktop/Magistrale/Tirocinio/Dati/3 - Methylation'
overall_survival: 'C:/Users/lucai/Desktop/Magistrale/Tirocinio/Dati/7 - Overall Survival'