gene_expression: '../../json_dir/files/gene_expression.json'
methylation: '../../json_dir/files/methylation.json'
overall_survival: '../../json_dir/files/overall_survival.json'
gene_expression_names: '../../json_dir/indexes/gene_expression_names.json'
methylation_names: '../../json_dir/indexes/methylation_names.json'
gene_expression_and_methylation_names: '../../json_dir/indexes/gene_expression_and_methylation_names.json'
gene_expression_and_methylation_statistics_names: '../../json_dir/indexes/gene_expression_and_methylation_statistics_names.json'
gene_expression_tss_names: '../../json_dir/indexes/gene_expression_tss_names.json'