gene_expression_json: 'C:/Users/lucai/Desktop/Magistrale/Tirocinio/Dati/2 - Gene Expression/gene_expression.json'
methylation_json: 'C:/Users/lucai/Desktop/Magistrale/Tirocinio/Dati/3 - Methylation/methylation.json'
overall_survival_json: 'C:/Users/lucai/Desktop/Magistrale/Tirocinio/Dati/7 - Overall Survival/overall_survival.json'