gene_expression_tss: '../../data/tables/gene_expression_tss.csv'
gene_expression: '../../data/tables/gene_expression.csv'
methylation: '../../data/tables/methylation.csv'
overall_survival: '../../data/tables/overall_survival.csv'