### JSON PATHS

## GENE EXPRESSION
# For binary classification
gene_expression: '../../data/datasets/gene_expression_and_overall_survival_dataset.csv'
# For MCAT
gene_expression_MCAT_wsi: '../../data/datasets/MCAT_gene_expression_and_wsi_and_overall_survival_dataset.csv'
# For MCAT/SurvPath
gene_expression_MCAT_methylation: '../../data/datasets/MCAT_gene_expression_and_overall_survival_dataset.csv'
# Original GUALTIERI Dataset
MCAT_gene_expression_and_overall_survival_dataset_GUALTIERI:


## METHYLATION
# For binary classification with 27k CpG islands
methylation27: '../../data/datasets/methylation27_and_overall_survival_dataset.csv'
# For binary classification with 450k CpG islands
methylation450: '../../data/datasets/methylation450_and_overall_survival_dataset.csv'
# For MCAT/SurvPath with 27k CpG islands of selected genes
methylation27_MCAT: '../../data/datasets/MCAT_methylation27_and_overall_survival_dataset.csv'
# For MCAT/SurvPath with 450k CpG islands of selected genes
methylation450_MCAT: '../../data/datasets/MCAT_methylation450_and_overall_survival_dataset.csv'
# For MCAT/SurvPath with 27k CpG islands
methylation27_full_MCAT: '../../data/datasets/MCAT_methylation27_full_and_overall_survival_dataset.csv'
# For MCAT/SurvPath with 450k CpG islands of selected genes
methylation450_full_MCAT: '../../data/datasets/MCAT_methylation450_full_and_overall_survival_dataset.csv'


## GENE EXPRESSION & METHYLATION
# For binary classification with 27k CpG islands of selected genes
gene_expression_and_methylation27: '../../data/datasets/gene_expression_and_methylation27_and_overall_survival_dataset.csv'
# For binary classification with 450k CpG islands of selected genes
gene_expression_and_methylation450: '../../data/datasets/gene_expression_and_methylation450_and_overall_survival_dataset.csv'
# For binary classification with 27k CpG islands of selected genes - Statistics
gene_expression_and_methylation27_statistics: '../../data/datasets/gene_expression_and_methylation27_statistics_and_overall_survival_dataset.csv'
# For binary classification with 450k CpG islands of selected genes - Statistics
gene_expression_and_methylation450_statistics: '../../data/datasets/gene_expression_and_methylation450_statistics_and_overall_survival_dataset.csv'