gene_expression: '../../data/datastores/gene_expression/gene_expression_data.json'
gene_expression_MCAT: '../../data/datastores/gene_expression/gene_expression_data_MCAT.json'
methylation: '../../data/datastores/methylation/methylation_data.json'
methylation_full_27_MCAT: '../../data/datastores/methylation/methylation_full_27_data_MCAT.json'
methylation_full_450_MCAT: '../../data/datastores/methylation/methylation_full_450_data_MCAT.json'
gene_associated_methylation_binary_classification: '../../data/datastores/methylation/gene_associated_methylation_data_binary_classification.json'
gene_associated_methylation_27: '../../data/datastores/methylation/gene_associated_methylation_data_27.json'
gene_associated_methylation_450: '../../data/datastores/methylation/gene_associated_methylation_data_450.json'
gene_associated_methylation_statistics: '../../data/datastores/methylation/gene_associated_methylation_statistics_data.json'
selected_methylation_islands: '../../data/datastores/methylation/selected_methylation_islands_data.json'
selected_methylation_islands_full: '../../data/datastores/methylation/selected_methylation_islands_data_full.json'
filter_methylation_list_27: '../../data/datastores/methylation/filter_methylation_list_27.json'
overall_survival: '../../data/datastores/overall_survival/overall_survival_data.json'
cpg950_coding_genes: '../../data/datastores/cpg950_coding_genes/cpg950_coding_genes_data.json'
cpg950_coding_genes_original: '../../data/datastores/cpg950_coding_genes/cpg950_coding_genes_original_data.json'
whole_slide_image: '../../data/datastores/whole_slide_image/whole_slide_image.json'