gene_expression: '../../data/datasets/gene_expression_and_overall_survival_dataset.csv'
gene_expression_MCAT_methylation: '../../data/datasets/MCAT_gene_expression_and_methylation_and_overall_survival_dataset.csv'
gene_expression_MCAT_wsi: '../../data/datasets/MCAT_gene_expression_and_wsi_and_overall_survival_dataset.csv'
methylation27: '../../data/datasets/methylation27_and_overall_survival_dataset.csv'
methylation450: '../../data/datasets/methylation450_and_overall_survival_dataset.csv'
methylation27_MCAT: '../../data/datasets/MCAT_methylation27_and_overall_survival_dataset.csv'
methylation450_MCAT: '../../data/datasets/MCAT_methylation450_and_overall_survival_dataset.csv'
gene_expression_and_methylation27: '../../data/datasets/gene_expression_and_methylation27_and_overall_survival_dataset.csv'
gene_expression_and_methylation450: '../../data/datasets/gene_expression_and_methylation450_and_overall_survival_dataset.csv'
gene_expression_and_methylation27_statistics: '../../data/datasets/gene_expression_and_methylation27_statistics_and_overall_survival_dataset.csv'
gene_expression_and_methylation450_statistics: '../../data/datasets/gene_expression_and_methylation450_statistics_and_overall_survival_dataset.csv'