### DATASTORE PATHS

## GENE EXPRESSION
# For binary classification
gene_expression: '../../data/datastores/gene_expression/gene_expression_data.json'
# For MCAT/SurvPath
gene_expression_MCAT: '../../data/datastores/gene_expression/gene_expression_data_MCAT.json'
# TSS of genes
cpg950_coding_genes: '../../data/datastores/cpg950_coding_genes/cpg950_coding_genes_data.json'
cpg950_coding_genes_original: '../../data/datastores/cpg950_coding_genes/cpg950_coding_genes_original_data.json'


## METHYLATION
# For binary classification
methylation: '../../data/datastores/methylation/methylation_data.json'
# For binary classification of genes associated
gene_associated_methylation_binary_classification: '../../data/datastores/methylation/gene_associated_methylation_data_binary_classification.json'
# For binary classification of genes associated - Statistics
gene_associated_methylation_statistics: '../../data/datastores/methylation/gene_associated_methylation_statistics_data.json'
# For MCAT/SurvPath with 27 CpG sites
methylation_full_27_MCAT: '../../data/datastores/methylation/methylation_full_27_data_MCAT.json'
# For MCAT/SurvPath with 450 CpG sites
methylation_full_450_MCAT: '../../data/datastores/methylation/methylation_full_450_data_MCAT.json'
# For MCAT/SurvPath with 27 CpG sites of genes associated
gene_associated_methylation_27: '../../data/datastores/methylation/gene_associated_methylation_data_27.json'
# For MCAT/SurvPath with 450 CpG sites of genes associated
gene_associated_methylation_450: '../../data/datastores/methylation/gene_associated_methylation_data_450.json'


## OVERALL SURVIVAL
# For all
overall_survival: '../../data/datastores/overall_survival/overall_survival_data.json'


## WHOLE SLIDE IMAGE
# For MCAT
whole_slide_image: '../../data/datastores/whole_slide_image/whole_slide_image.json'


## OTHERS
# Gene Associated Methylation Island
# Original selection
selected_methylation_islands: '../../data/datastores/methylation/selected_methylation_islands_data.json'
# My selection - Vector Size of 500
selected_methylation_islands_full: '../../data/datastores/methylation/selected_methylation_islands_data_full.json'
# My selection - Vector Size of 1000
MCAT_selected_methylation_islands: '../../data/datastores/methylation/MCAT_selected_methylation_islands_data.json'
# Other filter method
filter_methylation_list_27: '../../data/datastores/methylation/filter_methylation_list_27.json'