### JSON PATHS

## GENE EXPRESSION
gene_expression: '../../data/files/gene_expression'


## METHYLATION
methylation: '../../data/files/methylation'
methylation_original: '../../data/files/methylation_original'


## OVERALL SURVIVAL
overall_survival: '../../data/files/overall_survival'