gene_expression: '../../data/files/gene_expression'
methylation: '../../data/files/methylation'
methylation_original: '../../data/files/methylation_original'
overall_survival: '../../data/files/overall_survival'