### JSON PATHS

## GENE EXPRESSION
gene_expression: 'D:\Work\Università\Magistrale\6 - Tirocinio\Dati\KIRCKIRP\files\gene_expression'


## METHYLATION
methylation: 'D:\Work\Università\Magistrale\6 - Tirocinio\Dati\KIRCKIRP\files\methylation'
methylation_original: '../../data/files/methylation_original'


## OVERALL SURVIVAL
overall_survival: 'D:\Work\Università\Magistrale\6 - Tirocinio\Dati\KIRCKIRP\files\overall_survival'