### JSON PATHS

## GENE EXPRESSION
gene_expression: '../../json_dir/paths/gene_expression.json'
gene_expression_tss_names: '../../json_dir/indexes/gene_expression_tss_names.json'


## METHYLATION
methylation: '../../json_dir/paths/methylation.json'
methylation_original: '../../json_dir/paths/methylation_original.json'


## OVERALL SURVIVAL
overall_survival: '../../json_dir/paths/overall_survival.json'


## WHOLE SLIDE IMAGE
whole_slide_image: '../../json_dir/paths/whole_slide_image.json'