gene_expression: '../../json_dir/paths/gene_expression.json'
methylation: '../../json_dir/paths/methylation.json'
overall_survival: '../../json_dir/paths/overall_survival.json'
gene_expression_tss_names: '../../json_dir/indexes/gene_expression_tss_names.json'
whole_slide_image: '../../json_dir/paths/whole_slide_image.json'