gene_expression_keys_methylation: '../../data/signatures/gene_expression_keys_methylation.csv'
gene_expression_keys_wsi: '../../data/signatures/gene_expression_keys_wsi.csv'
methylation27_keys: '../../data/signatures/methylation27_keys.csv'
methylation27_full_keys: '../../data/signatures/methylation27_full_keys.csv'
methylation450_keys: '../../data/signatures/methylation450_keys.csv'
methylation450_full_keys: '../../data/signatures/methylation450_full_keys.csv'
gene_expression_lungs: '../../data/tables/ale_gene_expression_lungs.csv'
gene_expression_tss: '../../data/tables/gene_expression_tss.csv'
methylation_lungs: '../../data/tables/ale_methylation_lungs.csv'
methylation_vectors_for_each_gene: '../../data/tables/methylation_vectors_for_each_gene.csv'
methylation_vectors_for_each_gene_full: '../../data/tables/methylation_vectors_for_each_gene_full.csv'