gene_expression_keys: '../../data/tables/gene_expression_keys.csv'
gene_expression_lungs: '../../data/tables/ale_gene_expression_lungs.csv'
gene_expression_tss: '../../data/tables/gene_expression_tss.csv'
methylation_lungs: '../../data/tables/ale_methylation_lungs.csv'
methylation_vectors_for_each_gene: '../../data/tables/methylation_vectors_for_each_gene.csv'
methylation_vectors_for_each_gene_full: '../../data/tables/methylation_vectors_for_each_gene_full.csv'